name: Basic Continuous Integration (CI)

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Download TA-Lib Wheel
        run: |
          $wheel_url = "https://github.com/cgohlke/talib-build/releases/download/v0.6.3/ta_lib-0.6.3-cp311-cp311-win_amd64.whl" # Adjust version and Python if needed
          Invoke-WebRequest -Uri $wheel_url -OutFile "ta_lib.whl"
        shell: powershell

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir ta_lib.whl # Install the downloaded wheel
          pip install -r requirements.txt

      - name: Run tests
        run: python --version
